name: LINE Broadcast

on:
  schedule:
    # 例：毎日 11:55 UTC（日本時間 20:55）
    - cron: "55 11 * * *"
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Send broadcast
        env:
            LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
            # LINE_TEST_MODE: "true"
            # TEST_LINE_USER_ID: ${{ secrets.TEST_LINE_USER_ID }}
        run: |
          python daily_broadcast.py
